# This is a build spec to create or update multiple peering connection routes and route tables between different vpcs including inter-region multi-vpc peering connections
# This takes input from the vpc configurations file i.e vpc-config.yaml
version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get -y install python-pip
      - pip install awscli --upgrade --user
      - pip install boto3
      - pip install pyyaml
  build:
    commands:
      - echo Building application...
      - echo Building started on `date`
      - python ${UPDATE_ROUTE} ${VPC_CONFIGS}